Update jsonschema to the latest stable version
opentargets/validator pull request #26
Opened 2020-10-28 12:19 UTC by tskir

The `opentargets-validator` package currently has jsonschema pinned to version 3.0.0a3. Now that the latest stable version is 3.2.0, it starts to create some dependency resolution problems for projects which would like to use both the opentargets-validator and the latest jsonschema.

NB: I didn't verify that this change won't break something inside the validator. However, we're using jsonschema 3.2.0 to validate the evidence strings internally, and it seems to be working fine

2020-10-28 12:26 UTC, AsierGonzalez commented
I wonder why it was pinned to an specific release when the comment in the requirements file suggests that it was need a version that supports draft 7. I will verify that the update works.

2020-10-28 13:22 UTC, AsierGonzalez requested changes
Given that jsonschema started supporting schema version 7 in version 3.0.0, I suggest that the requirement changes to >=3.0.0.
@tskir would that be good enough to avoid the issues you are seeing or do you need >=3.2.0?

2020-10-28 13:38 UTC, tskir commented
@AsierGonzalez Yes, `>=3.0.0` would solve all problems for us, that would be great.

Although I suggest using at least `>=3.0.2` because there's a nasty comparison bug present prior to that, which is [fixed](https://github.com/Julian/jsonschema/blob/main/CHANGELOG.rst#v302) in 3.0.2.

2020-10-28 14:03 UTC, AsierGonzalez commented
I'm happy with that suggestion, if you make the change I'll approve the PR

2020-10-29 19:04 UTC, tskir commented
Done!

2020-10-30 00:09 UTC, AsierGonzalez approved these changes

2020-10-30 09:10 UTC, merged

2020-10-30 09:12 UTC, AsierGonzalez commented
Merged, thanks @tskir!